//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroNif.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CadastroNif.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem certeza?.
        /// </summary>
        internal static string EliminarCerteza {
            get {
                return ResourceManager.GetString("EliminarCerteza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao eliminar..
        /// </summary>
        internal static string EliminarErro {
            get {
                return ResourceManager.GetString("EliminarErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Eliminado com sucesso..
        /// </summary>
        internal static string EliminarSucesso {
            get {
                return ResourceManager.GetString("EliminarSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao gravar..
        /// </summary>
        internal static string GravadoErro {
            get {
                return ResourceManager.GetString("GravadoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gravado com sucesso..
        /// </summary>
        internal static string GravadoSucesso {
            get {
                return ResourceManager.GetString("GravadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao obter..
        /// </summary>
        internal static string ObterErro {
            get {
                return ResourceManager.GetString("ObterErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feminino.
        /// </summary>
        internal static string SexoFeminino {
            get {
                return ResourceManager.GetString("SexoFeminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Masculino.
        /// </summary>
        internal static string SexoMasculino {
            get {
                return ResourceManager.GetString("SexoMasculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Nascimento não pode ser superior nem igual a data de hoje..
        /// </summary>
        internal static string ValidaDadoDataNascimento {
            get {
                return ResourceManager.GetString("ValidaDadoDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Email não pode estar vazio..
        /// </summary>
        internal static string ValidaDadoEmail {
            get {
                return ResourceManager.GetString("ValidaDadoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Morada não pode estar vazio..
        /// </summary>
        internal static string ValidaDadoMorada {
            get {
                return ResourceManager.GetString("ValidaDadoMorada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Nome não pode estar vazio..
        /// </summary>
        internal static string ValidaDadoNome {
            get {
                return ResourceManager.GetString("ValidaDadoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Profissão não pode estar vazio..
        /// </summary>
        internal static string ValidaDadoProfissao {
            get {
                return ResourceManager.GetString("ValidaDadoProfissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Telefone não pode estar vazio..
        /// </summary>
        internal static string ValidaDadoTelefone {
            get {
                return ResourceManager.GetString("ValidaDadoTelefone", resourceCulture);
            }
        }
    }
}
